module.exports = [
  "Where missing socks go"
  "Female James Bond"
  "Fart house"
  "Eggmobile"
  "Imaginary friend"
  "You don't know Jack"
  "Kids in a musical"
  "Fringe crime"
  "Pizza cat"
  "Fairy tale"
  "Pure stank"
  "Fabio"
  "Emo duck"
  "Baby car"
  "Hodor!"
  "dat boi!"
  "funny tshirt"
  "missed high five"
  "secrets"
  "tiny ear man"
  "ear buddy"
  "bad advice elf"
  "sweet nothings"
  "man on fire"
  "a man on a wire"
  "fire in the hole"
  "bacon laser"
  "warehouse"
  "hovercraft"
  "mr. blobby"
  "pappa da poopy"
  "the cleaning lady comes on monday"
  "chris wants to see you in his office"
  "there's a snake in my boot"
]
