module.exports = {
  adjectives:[
    "cheesy"
    "funky"
    "manipulative"
    "invisible"
    "bad"
    "nice"
    "careless"
    "amusing"
    "flaming"
    "pooping"
    "dissappointing"
    "disgusting"
    "ungrateful"
    "slimy"
    "slippery"
    "squelchy"
    "squirty"
    "spunky"
    "aggressive"
    "twisted"
  ]
  nouns:[
    "seahorse"
    "manticore"
    "hat"
    "man"
    "cat"
    "star destroyer"
    "usain bolt"
    "boaty mcboatface"
    "ainsley harriot"
    "evaldas"
    "fruit bat"
    "wacko jacko"
    "man bear pig"
    "loch ness monster"
    "easter egg"
    "pizza"
    "ham"
    "badger"
    "frigemaster"
    "radiation"
  ]
  extras:[
    "on a skateboard"
    "with an icelolly"
    "on fire"
    "without a care"
    "playing twister"
    "sitting in a tree"
    "falling over"
    "bending over"
    "flying"
    "crying intensly"
    "loving life"
    "dying slowly"
    "drinking a special brew"
  ]
  prebuilds:[
    "where missing socks go"
    "female james bond"
    "fart house"
    "eggmobile"
    "imaginary friend"
    "you don't know jack"
    "kids in a musical"
    "fringe crime"
    "pizza cat"
    "fairy tale"
    "pure stank"
    "fabio"
    "emo duck"
    "baby car"
    "hodor!"
    "dat boi!"
    "funny tshirt"
    "missed high five"
    "secrets"
    "tiny ear man"
    "ear buddy"
    "bad advice elf"
    "sweet nothings"
    "man on fire"
    "a man on a wire"
    "fire in the hole"
    "bacon laser"
    "warehouse"
    "hovercraft"
    "mr. blobby"
    "pappa da poopy"
    "the cleaning lady comes on monday"
    "chris wants to see you in his office"
    "there's a snake in my boot"
    "fake plant"
    "wizard tower"
    "death by asphixiation"
    "tree fiddy"
    "banana phone"
    "bananas in pyjamas"
    "archery class"
    "foam motorycle"
    "nathan in his new job"
    "lady gaga"
  ]
}
